#!/bin/bash
export LD_LIBRARY_PATH="`pwd`/lib/linux64:${LD_LIBRARY_PATH}" # Only needed/works on Linux
# export JAVA_HOME="" # Set here if not set in environment
export JAVA_OPTS="-Xmx6G -Xms128M" # Set as much memory as possible
# Fix these if needed
export JCUDA_VERSION="0.4.2"
export JCUDA_LIBDIR=./lib
export LIBDIR=./lib

export BIDMAT_LIBS="./BIDMat.jar;${LIBDIR}/ptplot.jar;${LIBDIR}/ptplotapplication.jar;${LIBDIR}/jhdf5.jar"
export JCUDA_LIBS="${JCUDA_LIBDIR}/jcuda-${JCUDA_VERSION}.jar;${JCUDA_LIBDIR}/jcublas-${JCUDA_VERSION}.jar;${JCUDA_LIBDIR}/jcufft-${JCUDA_VERSION}.jar;${JCUDA_LIBDIR}/jcurand-${JCUDA_VERSION}.jar;${JCUDA_LIBDIR}/jcusparse-${JCUDA_VERSION}.jar"

export ALL_LIBS="${BIDMAT_LIBS};${JCUDA_LIBS};${JAVA_HOME}/lib/tools.jar"

if [ ! "$OS" = "Windows_NT" ]; then
    export ALL_LIBS=`echo "${ALL_LIBS}" | sed 's/;/:/g'`
fi

 scala -nobootcp -cp "${ALL_LIBS}" -Yrepl-sync -i ${LIBDIR}/bidmat_init.scala